format = """\
    󰣇 \
    $username \
    $time \
    $git_branch$git_commit$git_state$git_status \
    \n\
    $directory \
    $character\
"""

# <<================================================================>>

[directory]
disabled = false
format = "[$path](bold fg:#8be9fd)"
truncate_to_repo = false

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '(\[[$all_status$ahead_behind]($style)\])'

[time]
disabled = false
format = '\[[$time]($style)\]'
time_format = "%R"

[username]
disabled = false
format = '\[[$user]($style)\]'
show_always = true