# "$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
format = """\
  󰣇 \
  $username\
  $time\
  $git_branch$git_commit$git_state $git_status\
  $aws\
  $azure\
  $buf\
  $c\
  $cpp\
  $cmake\
  $cobol\
  $conda\
  $crystal\
  $custom\
  $daml\
  $dart\
  $deno\
  $dotnet\
  $elixir\
  $elm\
  $erlang\
  $fennel\
  $gcloud\
  $golang\
  $guix_shell\
  $gradle\
  $haskell\
  $haxe\
  $helm\
  $hg_branch\
  $java\
  $julia\
  $kotlin\
  $kubernetes\
  $lua\
  $memory_usage\
  $meson\
  $nim\
  $nodejs\
  $ocaml\
  $opa\
  $openstack\
  $os\
  $perl\
  $php\
  $pijul_channel\
  $pixi\
  $pulumi\
  $purescript\
  $python\
  $raku\
  $red\
  $rlang\
  $ruby\
  $rust\
  $scala\
  $singularity\
  $solidity\
  $spack\
  $status\
  $swift\
  $terraform\
  $vagrant\
  $vcsh\
  $vlang\
  $zig\
  \n\
  $directory \
  $character\

"""


continuation_prompt = '▶▶ '

# style_choices:
# bold
# italic
# underline
# dimmed
# inverted
# blink
# hidden
# strikethrough
# bg:<color>
# fg:<color>
# <color>
# none

# <<==================================================================================>>

[username]
disabled = false
format = '[$user ]($style)'
show_always = true

[time]
disabled = false
format = '[[  $time ](fg:#a0a9cb )]($style)'
time_format = "%R"                            # Hour:Minute Format

[git_branch]
format = " [  $branch](fg:#9198a1)"

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[( $all_status$ahead_behind )](fg:#769ff0)]($style)'
style = "bg:#394260"

# <<==================================================================================>>
# <<==================================================================================>>

[aws]
disabled = false
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"
symbol = " "

# <<==================================================================================>>


[buf]
style = "bold bright-red"
format = " [buf](italic) [$symbol $buf_version]($style)"
symbol = "■ "

# <<==================================================================================>>

[c]
detect_extensions = [".c", "h"]
style = "bold bright-cyan"
format = " [$symbol($version(-$name))]($style)"
symbol = "ℂ "

[cpp]
detect_extensions = ["cpp", "h"]
style = "bold bright-cyan"
format = " [$symbol($version)]($style)"
symbol = "ℂ++ "

[conda]
format = " conda [$symbol$environment]($style)"
symbol = "◯ "

# <<==================================================================================>>

[dart]
format = " dart [$symbol($version )]($style)"
symbol = " "

[deno]
style = "italic green"
format = "[$symbol($version)]($style)"
symbol = " "

# <<==================================================================================>>

[elixir]
format = " exs [$symbol $version OTP $otp_version ]($style)"
symbol = " "

[elm]
format = " elm [$symbol($version )]($style)"
symbol = "◩ "

# <<==================================================================================>>

[golang]
format = " go [$symbol($version )]($style)"
symbol = "∩ "

# <<==================================================================================>>

[haskell]
format = " hs [$symbol($version )]($style)"
symbol = "❯λ "

# <<==================================================================================>>

[java]
format = " java [${symbol}(${version} )]($style)"
symbol = " "

[julia]
format = " jl [$symbol($version )]($style)"
symbol = "◎ "

# <<==================================================================================>>

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
style = "bold bright-yellow"
symbol = "⨀ "
version_format = "${raw}"

# <<==================================================================================>>

[memory_usage]
format = " mem [${ram}( ${swap})]($style)"
symbol = "▪▫▪ "

# <<==================================================================================>>

[nim]
format = " nim [$symbol($version )]($style)"
symbol = "▴▲▴ "

[nix_shell]
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
style = 'bold italic dimmed blue'
symbol = ' '
unknown_msg = '[◌](bold dimmed ellow)'

[nodejs]
detect_extensions = []
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
format = "[ $version](bold bright-green)"
version_format = "${raw}"

# <<==================================================================================>>

[python]
format = "[${symbol}(${virtualenv}) ${version}]($style)"
style = "bold bright-yellow"
symbol = "[ ](bold bright-blue)"
version_format = "${raw}"

# <<==================================================================================>>

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
style = "bold red"
symbol = " "
version_format = "${raw}"

[rust]
format = " rs $symbol"
symbol = " "

# <<==================================================================================>>

[scala]
format = " scala [$symbol]($style)"
symbol = " "

[spack]
format = " spack [$symbol$environment]($style)"
symbol = "◇ "

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
style = "bold bright-red"
symbol = " "
version_format = "${raw}"

# <<==================================================================================>>

[zig]
format = " zig [$symbol]($style)"
symbol = " "

# <<==================================================================================>>
# <<==================================================================================>>

[directory]
disabled = false
format = "[$path](bold fg:#8be9fd)"
truncate_to_repo = false 

# [character]       #NOTE: you can customize the symbols
# success_symbol = "[  ]($bold fg:#f8f8f2)"
# error_symbol = "[  ]($bold fg:#fb4934)